/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)
**/
const express = require("express");
const bodyParser = require("body-parser");
const todos = require("./todos.json");
const fs = require("fs");
const { v4: uuidv4 } = require('uuid');

const app = express();

app.use(bodyParser.json());

function filterTodoById(id) {
  return todos.filter((item) => id == item.id);
}
/**
  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    **/
app.get("/todos", async (req, res) => {
  let allTodos = await fs.promises.readFile('./todos.json', 'utf8')
  // console.log(allTodos.length)
  res.json(JSON.parse(allTodos));
});

/**
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    **/
app.get("/todos/:id", async (req, res) => {
  let { id } = req.params;
  let allTodos = await fs.promises.readFile('./todos.json', 'utf8');
  let filteredItems = JSON.parse(allTodos)
  filteredItems = filteredItems.filter(item => item.id == id);
  // let filteredItems = filterTodoById(id);
  if (!filteredItems.length > 0) {
    res.status(404).send("Todo Not found");
  } else {
    console.log(filteredItems[0].id)
    console.log('there is found item of length: ', filteredItems.length);
    res.json(filteredItems[0]);
  }
});
/**
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    **/
app.post("/todos", async (req, res) => {
  let wholeTextContainer = [];
  let allTodos = JSON.parse(await fs.promises.readFile('./todos.json', 'utf8'))
  let newText = { id: uuidv4(), ...req.body };
  try {
    let isTodoAlreadyPresent = filterTodoById(newText.id);
    if (isTodoAlreadyPresent.length > 0) {
      res.status(403).json({ message: "todo already present" });
    } else {
      wholeTextContainer = [...allTodos, newText];
      await fs.promises.writeFile(
        "./todos.json",
        JSON.stringify(wholeTextContainer)
      );
    }
  } catch (error) {
    console.log(error);
  }
  res.status(201).json(newText);
});
/**
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    **/
app.put("/todos/:id", async (req, res) => {
  let id = req.params.id;
  let { title, description } = req.body;
  let wholeTextContainer;

  let allTodos = await fs.promises.readFile('./todos.json', 'utf8');
  let isTodoAlreadyPresent = JSON.parse(allTodos).filter(item => item.id == id);
  if (isTodoAlreadyPresent) {
    try {
      wholeTextContainer = [{ ...isTodoAlreadyPresent[0], title, description }]
      console.log(wholeTextContainer)
      fs.promises.writeFile("./todos.json", JSON.stringify(wholeTextContainer));
      res.json({ message: 'todo updated' })
    } catch (error) {
      console.log(error);
    }
  } else {
    res.status(404).json({ message: "Not found" });
  }
});
/**
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */

app.delete('/todos/:id', async (req, res) => {
  const { id } = req.params;
  let allTodos = JSON.parse(await fs.promises.readFile('./todos.json', 'utf8'))
  let index = allTodos.findIndex(item => item.id == id);

  const newArrayOfDeletedTodo = await allTodos.splice(index, 1);

  // console.log(allTodos);
  // res.json({alltodos: allTodos, newdelarr:newArrayOfDeletedTodo})

  await fs.promises.writeFile('./todos.json', JSON.stringify(allTodos));

  res.json({ message: 'todo deleted' })
})

app.get('*', (req, res) => res.status(404).json({ message: 'Todo not existed' }))

app.listen(8001, () => console.log("listening at 8001"));
module.exports = app;
